sudo: required
services:
    - docker

before_install:
    - docker build -t moodyjeff/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true moodyjeff/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ca-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: elasticbeanstalk-ca-central-1-941119734485
    bucket_pack: "docker-react"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
